on:
  issue_comment:
    types: [created]
jobs:
  commentCreated:
    runs-on: self-hosted
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes
          
      - name: Print content
        env:
          BODY: ${{ github.event.comment.body }}
        run: echo "$BODY"
